version: '{build}'
image: Visual Studio 2017

branches:
  only:
  - master
  - develop

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: .\build.ps1

artifacts:
- path: '.\artifacts\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: po+cN8gEO7ami/vMXGuZ0WiYJHzB6AoJCD0Cdq78XXRh/o9JNZKcV3MSgoxmBiMs 
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: /^(master|develop)$/
